default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: sunny_sundays
  host: localhost
  port: 5432
  username: fgallo
  password: your_password_5

test:
  <<: *default
  database: sunny_sundays_test
  host: localhost
  port: 5432
  username: fgallo
  password: your_password_5

production:
  <<: *default
  database: sunny_sundays_production
  host: localhost
  port: 5432
  username: fgallo
  password: your_password_5
